### ISSUE TITLE
Processamento de maratona-editores-cuba - returned an error code

### ISSUE THREAD

**Issue by dheysonalves** [maratona-linux/maratona-linux#1]
Estava instalando na vm Ubuntu 18.04 LTS, mas durante a instalação retornou este erro. Apenas instalei a máquina virtual, atualizei e comecei atualização. Nenhuma configuração extra antes disso:
`E:Sub-process /usr/bin/dpkg returned an error code (1)`

![image](https://user-images.githubusercontent.com/30505432/57157987-9869ee80-6db8-11e9-9e6b-5a6a4a9bec92.png)

Sabe me dizer como devo proceder?

**Comment by bcribas** [comment]
Oi @Dheyson , o pacote `maratona-editores-cuba` é opcional, você pode instalar o pacote `maratona-desktop` da seguinte forma:

```.bash
sudo apt-get install maratona-desktop maratona-editores-cuba-
```

Note o *-* depois da palavra cuba. Dessa forma o pacote não será instalado e não acontecerá problema.

Eu vou gerar uma atualização para corrigir esste problema assim que eu tiver um tempo para respirar.

[]s

**Comment by wallberg13** [comment]
Bruno, pode ser que o NetBeans tenha atualizado, e por isso está dando esse
erro.

**Comment by bcribas** [comment]
O pacote `maratona-editores-cuba` agora é Suggests dos pacote `maratona-editores`, dessa forma ele não será instalado automaticamente mais.

O plano é remover o pacote completamente, de acordo com a reunião que fizemos da LATAM em março. Por ora apliquei a modificação que causa menos impacto na estrutura dos pacotes (para evitar algum bug qualquer).

Fiz o upload do pacote para o repositório no launchpad, assim o PPA já está atualizado.
