### ISSUE TITLE
"The repository 'http://ppa.launchpad.net/brunoribas/ppa-maratona/ubuntu bionic Release' does not have a Release file."

### ISSUE THREAD

**Issue by JayPOS** [maratona-linux/maratona-linux#2]
Estou tentando adicionar o repositório aqui porém dá esse erro e um amigo também teve esse problema ao atualizar um servidor com o boca dele

**Comment by bcribas** [comment]
Olá,

Os pacotes funcionam em Ubutun 18.04 e o novo repositório é: ppa:icpc-latam/maratona-linux

Para adicionar basta rodar:
```
sudo add-apt-repository ppa:icpc-latam/maratona-linux
```

Lembrando que sempre deve ser em um Ubuntu 18.04 64bits.
