### ISSUE TITLE
Erro ao adicionar o ppa

### ISSUE THREAD

**Issue by JayPOS** [maratona-linux/maratona-linux#3]
Estou ainda tendo o erro que relatei na ultima issue, mas mandarei prints agora para esclarecer oq eu estou fazendo. a maquina que estou usando, é um ubuntu 18.04 com 64 bits, e o repositório que estou tentando adicionar é ppa:icpc-latam/maratona-linux

![Captura de tela de 2019-10-28 02-05-32](https://user-images.githubusercontent.com/40281339/67653326-acd21280-f927-11e9-96db-f98360b7cbeb.png)
![Captura de tela de 2019-10-28 02-04-51](https://user-images.githubusercontent.com/40281339/67653327-acd21280-f927-11e9-882b-2cb7e3c90304.png)

**Comment by bcribas** [comment]
O erro que você está tendo ainda é do repositório antigo, vai ter que removê-lo:
```
sudo add-apt-repository -r  ppa:brunoribas/ppa-maratona
```

**Comment by JayPOS** [comment]
Okay, agora funcionou, obrigado!
